[package]
name = "sophon-boot-uefi"
version = "0.0.1"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = "2018"

[[bin]]
name = "sophon-boot-uefi"
path = "src/main.rs"

[dependencies]
spin = "0.7"
cortex-a = "7.4.0"
tock-registers = "0.7.0"
uefi = { version = "0.16.0", features = ["exts", "alloc"] }
uefi-services = "0.13.0"
elf_rs = "0.1.1"
memory = { path = "../../libs/memory" }
boot = { path = "../../libs/boot" }
log = { path = "../../libs/log" }
fdt = "0.1.3"