cargo-features = ["workspace-inheritance"]

[package]
name = "sophon-boot-uefi"
version = "0.0.1"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = "2018"

[[bin]]
name = "sophon-boot-uefi"
path = "src/main.rs"

[dependencies]
spin = { workspace = true }
cortex-a = { workspace = true }
tock-registers = { workspace = true }
uefi = { workspace = true }
uefi-services = { workspace = true }
elf_rs = { workspace = true }
fdt = { workspace = true }
memory = { path = "../../libs/memory" }
boot = { path = "../../libs/boot" }
log = { path = "../../libs/log" }