[package]
name = "sophon-boot-uefi"
version = "0.0.1"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = "2018"

[[bin]]
name = "sophon-boot-uefi"
path = "src/main.rs"

[dependencies]
spin = "0.7"
cortex-a = "6.0.0"
tock-registers = "0.7.0"
uefi = { version = "0.11.0", features = ["exts", "alloc"] }
uefi-services = "0.8.0"
elf_rs = "0.1.1"
sophon = { path = "../../sophon", features = ["kernel"] }
fdt = "0.1.3"