[package]
name = "sophon"
version = "0.0.1"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = "2018"

[[bin]]
name = "sophon"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.2"
cortex-a = "6.0.0"
tock-registers = "0.7.0"
elf_rs = "0.1.3"
fdt = "0.1.3"
serde = { version = "1.0", default-features = false }
postcard = { version = "0.7.0", features = ["alloc"] }
ipc = { path = "../libs/ipc" }
memory = { path = "../libs/memory" }

[build-dependencies]
spin = "0.9.2"
serde = { version = "1.0", default-features = false }
postcard = { version = "0.7.0", features = ["alloc"] }
yaml-rust = "0.4"

[features]
default = []
kernel = []