[package]
name = "sophon"
version = "0.0.1"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.3"
cortex-a = "7.4.0"
tock-registers = "0.7.0"
elf_rs = "0.2.0"
fdt = "0.1.3"
serde = { version = "1.0", default-features = false }
postcard = { version = "1.0.0", features = ["alloc"] }
ipc = { path = "../libs/ipc" }
memory = { path = "../libs/memory" }
interrupt = { path = "../libs/interrupt" }
log = { path = "../libs/log" }
boot = { path = "../libs/boot" }
atomic = "0.5"
crossbeam = { version = "0.8.1", default-features = false, features = ["alloc"] }
hashbrown = "0.12"

[build-dependencies]
spin = "0.9.3"
serde = { version = "1.0", default-features = false }
postcard = { version = "1.0.0", features = ["alloc"] }
yaml-rust = "0.4.5"

[features]
default = []
disable_log = ["log/disable"]