[workspace]
members = [
# Kernel
    "sophon",
# Libraries
    "libs/bitflags",
    "libs/boot",
    "libs/heap",
    "libs/interrupt",
    "libs/ipc",
    "libs/log",
    "libs/memory",
# Tools
    "tools/dev",
# Boot loaders
    "boot/uefi",
# User programs
    "user/init",
    "user/scheme_test",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1