[workspace]
members = [
    "sophon",
    "libs/bitflags",
    "libs/heap",
    "libs/interrupt",
    "libs/ipc",
    "libs/memory",
    "tools/initfs_builder",
    "boot/uefi",
    "user/init",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
lto = true
codegen-units = 1