[package]
name = "proton"
version = "0.1.0"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.5.2"
cortex-a = "2.7.0"
bitflags = "1.2.1"
goblin = { version = "0.1.0", default-features = false, features = ["elf32", "elf64", "endian_fd"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[features]
default = []
rls = []
qemu = []
raspi3 = []
raspi4 = []