[workspace]
members = [
    "kernel",
    "proton",
    "arch/aarch64",
    "init",
    "drivers/emmc"
]

[profile.dev]
panic = "abort"
# opt-level = 1

[profile.release]
debug = true
panic = "abort"
# lto = true