cargo-features = ["workspace-inheritance"]

[package]
name = "hello"
version = { workspace = true }
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
user = { path = "../../libs/user" }

[features]
default = []