[package]
name = "dev"
version = "0.0.1"
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xshell = "0.1.17"
clap = { package = "clap-v3", version = "3.0.0-beta.1" }
spin = "0.9.2"
serde = { version = "1.0", default-features = false }
postcard = { version = "0.7.0", features = ["alloc"] }
yaml-rust = "0.4"