on: [push, pull_request]
name: Style Check
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
      - name: Format Check
        run: cargo fmt --all --check
