on: [push, pull_request]
name: Style Check
jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: codota/toolchain@v1
      - name: Cargo format check
        run: cargo fmt --all --check
