on: [push, pull_request]
name: Style Check
jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: oxidecomputer/actions-rs_toolchain@v1
      - name: Format Check
        run: cargo fmt --all --check
